default:
  #start_time: "2020/04/03"
  start_time: "2021/08/20"
  #end_time: "2021/09/17"
  end_time: "2021/08/24"
  file_add_and_name: './data/Folkhalsomyndigheten_Covid19_'
  # Sheet type
  Antal per dag region: 1
  Antal avlidna per dag: 1
  Antal intensivvårdade per dag: 1
  Totalt antal per region: 2
  Totalt antal per kön: 2
  Totalt antal per åldersgrupp: 2
  Veckodata Region: 3
  Veckodata Kommun_stadsdel: 3
  Veckodata Riket: 3
  # Combined sheet
  Antal per dag region/kön: [1,5]
 
 
